# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemindMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemindMe
    
     pod 'Parse'
     pod 'AlamofireImage'
     pod 'MessageInputBar'

  target 'RemindMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemindMeUITests' do
    # Pods for testing
  end

end
